# -*- coding: utf-8 -*-
"""runbatchDEFScontext

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIQEE01XtusjYDZhlzRl8uhZfdco9Og4
"""



from transformers import pipeline
import torch

chat_models = ["mistralai/Mathstral-7b-v0.1",
               "Salesforce/E1-Math-1.5B",
               "kfdong/STP_model_Lean_0320",
               "deepseek-ai/deepseek-math-7b-instruct",
               "deepseek-ai/DeepSeek-Prover-V2-7B",
               "deepseek-ai/DeepSeek-Prover-V2-671B",
               "Qwen/Qwen2.5-Math-72B-Instruct",
               "haielab/DeepSeek-Prover-V2-7B-2ndEpoch-conjecture-base",
               "haielab/DeepSeek-Prover-V2-7B-2ndfinal-conjecture-base",
               "haielab/DeepSeek-Prover-V2-7B-conjecture-base-FineTune-new-config",
               "haielab/DeepSeek-Prover-V2-7B-conjecture-base-FineTune-new-config-conjecture-base-FineTune-new-config-v2"]
base_models = ["EleutherAI/llemma_7b",
               "EleutherAI/llemma_34b",
               "MathLLMs/MathCoder-L-7B",
               "MathGenie/MathGenie-Mixtral-8x7B",
               "WizardLMTeam/WizardMath-7B-V1.1",
               "WizardLMTeam/WizardMath-70B-V1.0",
               "Qwen/Qwen2.5-Math-7B",
               "bytedance-research/BFS-Prover"]
other_models = ["internlm/internlm2-math-plus-7b"]
checkpoint = "haielab/DeepSeek-Prover-V2-7B-conjecture-base-FineTune-new-config-conjecture-base-FineTune-new-config-v2"
max_tokens = 4096

if checkpoint in other_models:
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(checkpoint, trust_remote_code=True)
    pipe = pipeline("text-generation", checkpoint, trust_remote_code=True, device_map="auto", tokenizer=tok,
                    torch_dtype=torch.bfloat16)
else:
    pipe = pipeline("text-generation", checkpoint, trust_remote_code=True, device_map="auto",
                    torch_dtype=torch.bfloat16)

# Commented out IPython magic to ensure Python compatibility.
# abstract_1 = """ Suppose N is a phylogenetic network indicating a complicated relationship
# among individuals and taxa. Often of interest is a much simpler network, for
# example, a species tree T, that summarizes the most fundamental relationships.
# The meaning of a species tree is made more complicated by the recent discovery
# of the importance of hybridizations and lateral gene transfers. Hence it is
# desirable to describe uniform well-defined procedures that yield a tree given a
# network N. A useful tool toward this end is a connected surjective digraph
# (CSD) map f from N to N' where N' is generally a much simpler network than N. A
# set W of vertices in N is "restricted" if there is at most one vertex from
# which there is an arc into W, thus yielding a bottleneck in N. A CSD map f from
# N to N' is "restricted" if the inverse image of each vertex in N' is restricted
# in N. This paper describes a uniform procedure that, given a network N, yields
# a well-defined tree called the "restricted tree" of N. There is a restricted
# CSD map from N to the restricted tree. Many relationships in the tree can be
# proved to appear also in N. """
# abstract_2 = """ In this article, we investigate bijections on various classes of set
# partitions of classical types that preserve openers and closers. On the one
# hand we present bijections that interchange crossings and nestings. For types B
# and C, they generalize a construction by Kasraoui and Zeng for type A, whereas
# for type D, we were only able to construct a bijection between non-crossing and
# non-nesting set partitions. On the other hand we generalize a bijection to type
# B and C that interchanges the cardinality of the maximal crossing with the
# cardinality of the maximal nesting, as given by Chen, Deng, Du, Stanley and Yan
# for type A. Using a variant of this bijection, we also settle a conjecture by
# Soll and Welker concerning generalized type B triangulations and symmetric fans
# of Dyck paths. """
# abstract_3 = """ Let G be a graph with n vertices, and let k be an integer dividing n. G is
# said to be strongly k-colorable if for every partition of V(G) into disjoint
# sets V_1 \cup ... \cup V_r, all of size exactly k, there exists a proper vertex
# k-coloring of G with each color appearing exactly once in each V_i. In the case
# when k does not divide n, G is defined to be strongly k-colorable if the graph
# obtained by adding k \lceil n/k \rceil - n isolated vertices is strongly
# k-colorable. The strong chromatic number of G is the minimum k for which G is
# strongly k-colorable. In this paper, we study the behavior of this parameter
# for the random graph G(n, p). In the dense case when p >> n^{-1/3}, we prove
# that the strong chromatic number is a.s. concentrated on one value \Delta+1,
# where \Delta is the maximum degree of the graph. We also obtain several weaker
# results for sparse random graphs. """
# abstract_4 = """ Let $M_n$ be an $n$ by $n$ random matrix where each entry is +1 or -1
# independently with probability 1/2. Our main result implies that the
# probability that $M_n$ is singular is at most $(1/\sqrt{2} + o(1))^n$,
# improving on the previous best upper bound of $(3/4 + o(1))^n$ proven by Tao
# and Vu in arXiv:math/0501313v2. This paper follows a similar approach to the
# Tao and Vu result, including using a variant of their structure theorem. We
# also extend this type of exponential upper bound on the probability that a
# random matrix is singular to a large class of discrete random matrices taking
# values in the complex numbers, where the entries are independent but are not
# necessarily identically distributed. """
# abstract_5 = """ A {\it heterochromatic tree} is an edge-colored tree in which any two edges
# have different colors. The {\it heterochromatic tree partition number} of an
# $r$-edge-colored graph $G$, denoted by $t_r(G)$, is the minimum positive
# integer $p$ such that whenever the edges of the graph $G$ are colored with $r$
# colors, the vertices of $G$ can be covered by at most $p$ vertex-disjoint
# heterochromatic trees. In this paper we determine the heterochromatic tree
# partition number of an $r$-edge-colored complete graph. """
# abstract_6 = """ Let ccl(G) denote the order of the largest complete minor in a graph G (also
# called the contraction clique number) and let G(n,p) denote a random graph on n
# vertices with edge probability p. Bollobas, Catlin and Erdos asymptotically
# determined ccl(G (n,p)) when p is a constant. Luczak, Pittel and Wierman gave
# bounds on ccl(G(n,p)) when p is very close to 1/n, i.e. inside the phase
# transition. Extending the results of Bollobas, Catlin and Erdos, we determine
# ccl(G(n,p)) quite tightly, for p>C/n where C is a large constant. If p=C/n, for
# an arbitrary constant C>1, then we show that asymptotically almost surely ccl(G
# (n,p)) is of order square-root of n. This answers a question of Krivelevich and
# Sudakov. """
# abstract_7 = """ Let $G=(V,E)$ be an undirected graph without loops and multiple edges. A
# subset $C\subseteq V$ is called \emph{identifying} if for every vertex $x\in V$
# the intersection of $C$ and the closed neighbourhood of $x$ is nonempty, and
# these intersections are different for different vertices $x$.
#   Let $k$ be a positive integer. We will consider graphs where \emph{every}
# $k$-subset is identifying. We prove that for every $k>1$ the maximal order of
# such a graph is at most $2k-2.$ Constructions attaining the maximal order are
# given for infinitely many values of $k.$
#   The corresponding problem of $k$-subsets identifying any at most $\ell$
# vertices is considered as well. """
# abstract_8 = """  """
# abstract_9 = """  """
# abstract_10 = """  """
# 
# context_1 = r""" human population forms a tight cluster.  If $N$ is successively cluster-distinct, the same argument would suggest that it forms a restricted set.
# 
# A restricted CSD map $f: N \to N'$ is \emph{universal (for restricted maps)} provided that given any restricted map $g: N \to N''$  there is a unique restricted CSD map $h: N' \to N''$ such that $g = h \circ f$.
# 
# We shall see below that the natural projection map $\phi: N \to ResTr(N)$ is universal for restricted maps.
# 
# The first result is that the image of a restricted map is always a tree.
# 
# \begin{thm}%4.1
# Let $N=(V,A,r,X)$ be an acyclic $X$-network and let $T = (V',A',r',X)$ be an $X$-network.  Assume $f: N \to T$ is a restricted CSD map.  Then $T$ is a tree.
# \end{thm}
# 
# \begin{proof}
# We show that $T$ has no hybrid vertices.  Suppose otherwise, so we may assume $V'$ contains distinct vertices $u_1'$, $u_2'$, and $u_3'$ while $A'$ contains arcs $(u_1',u_3')$, $(u_2', u_3')$.  Let $B_i = f^{-1}(u_i')$.  Since $f$ is restricted, each $B_i$ is a restricted set.  Since $f$ is a CSD map, there exist $u_1 \in B_1$, $w_1 \in B_3$, $u_2 \in B_2$, and  $w_2 \in B_3$ such that $(u_1,w_1)$ and $(u_2,w_2)$ are arcs of $N$.  Note $u_1 \notin B_3$ and $u_2 \notin B_3$.  Since $B_3$ is restricted, it follows $u_1 = Anc(B_3)$ and $u_2 = Anc(B_3)$.  Hence $u_1 = u_2$ so $u_1' = f(u_1) = f(u_2) = u_2'$, a contradiction.
# \end{proof}
# 
# 
# \begin{cor}%Cor 4.2.
# Let $N=(V,A,r,X)$ be an acyclic $X$-network.  Then $ResTr(N)$ is an $X$-tree.
# \end{cor}
# 
# \begin{proof}
# The natural projection map $\phi: N \to ResTr(N)$ is a restricted CSD map.
# \end{proof}
# 
# 
# The next result shows that many relationships among leaves observed in $ResTr(N)$ are also present in $N$.
# 
# \begin{cor}%Cor 4.3.
# Let $N=(V,A,r,X)$ be an acyclic $X$-network.  There is a wired lift of $ResTr(N)$ into $N$.
# \end{cor}
# 
# \begin{proof}
# This follows from Theorem 2.5.
# \end{proof}
# 
# 
# Restricted maps have interesting functorial properties, as seen in the next results. """
# context_2 = r"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# \section{Crossings and nestings in set partitions of type $A$}
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# \label{sec:cross-nest-A}
# 
# One of the goals of this article is to refine the following well known correspondences between
# non-crossing and non-nesting set partitions.  For ordinary set partitions, a
# \Dfn{crossing} consists of a pair of arcs $(i,j)$ and $(i',j')$ such that
# $i<i'<j<j'$:
# \begin{center}
#   \setlength{\unitlength}{20pt}
#   \begin{picture}(12,2.2)
#     \put(0,0){\hbox{$1$}}
#     \put(1,0){\hbox{$\ldots$}}
#     \put(2.5,0){\hbox{$i$}}
#     \put(3.5,0){\hbox{$<$}}
#     \put(4.75,0){\hbox{$i'$}}
#     \put(5.75,0){\hbox{$<$}}
#     \put(7,0){\hbox{$j$}}
#     \put(8,0){\hbox{$<$}}
#     \put(9.25,0){\hbox{$j'$}}
#     \put(10.25,0){\hbox{$\ldots$}}
#     \put(11.75,0){\hbox{$n$}}
#     \qbezier(2.9,0.7)(4.9,3.2)(6.9,0.7)
#     \qbezier(5.1,0.7)(7.1,3.2)(9.1,0.7)
#   \end{picture}
#   % \input{NCcounter.tex}
# \end{center}
# On the other hand, if $i<i'<j'<j$, we have a \Dfn{nesting}, pictorially:
# \begin{center}
#   \setlength{\unitlength}{20pt}
#   \begin{picture}(12,2.2)
#     \put(0,0){\hbox{$1$}}
#     \put(1,0){\hbox{$\ldots$}}
#     \put(2.5,0){\hbox{$i$}}
#     \put(3.5,0){\hbox{$<$}}
#     \put(4.75,0){\hbox{$i'$}}
#     \put(5.75,0){\hbox{$<$}}
#     \put(7,0){\hbox{$j'$}}
#     \put(8,0){\hbox{$<$}}
#     \put(9.25,0){\hbox{$j$}}
#     \put(10.25,0){\hbox{$\ldots$}}
#     \put(11.75,0){\hbox{$n$}}
#     \qbezier(2.9,0.7)(6.0,3.2)(9.1,0.7)
#     \qbezier(5.1,0.7)(6.0,2.2)(6.9,0.7)
#   \end{picture}
#   % \input{NNcounter.tex}
# \end{center}
# A set partition of $[n]$ is called \Dfn{non-crossing} (resp. \Dfn{non-nesting})
# if the number of crossings (resp. the number of nestings) equals $0$.
# 
# It has been known for a long time that the numbers of non-crossing and
# non-nesting set-partitions of $[n]$ coincide.  More recently, Anisse Kasraoui
# and Jiang Zeng have shown in~\cite{KasraouiZeng2006} that much more is true:
#   """
# context_3 = r"""(\sigma \frac{\Delta}{\log
#   n}\big) = o(\Delta)$ neighbors in $V_j$, since $\sigma \leq \frac{2 \log n}{\log \log
#   n}$.  Also, by construction of $I_1$, every part whose index is not in $I_1$ has at most
# $\frac{\ep}{4} \Delta$ locally big vertices.  Hence the size of $V'_j$ is at least $|V_j|
# -(1+o(1)) \Delta - \frac{\ep}{4} \Delta \geq \frac{\ep}{2} \Delta$, as claimed.
# 
# Let us say that a set $U_t$ satisfies property $\mathbf{Q}_t$ if for every $k \not \in
# I_1 \cup J_t$, all the vertices in $U_t$ that
# are not locally big with respect to $V_k$ have together at most
# $300 (\tau - t)\frac{\Delta}{\log n}$ neighbors in $V_k$.
# We need the following  analogue of Lemma \ref{lem:first-stage}.
# \begin{lemma}
#   \label{lem:second-stage}
#   Suppose $t > 1$, and $U_t$ is an independent transversal on $V'_{J_t}$ which satisfies
#   $\mathbf{Q}_t$.  Then we can extend $U_t$ to $U_{t-1}$, an independent transversal on
#   $V'_{J_{t-1}}$ which satisfies $\mathbf{Q}_{t-1}$.
# \end{lemma}
# We also postpone the proof of this lemma until Section \ref{sec:last-lemma}.
# Starting with $U_\tau = \emptyset$, we iterate this lemma until we obtain $U_1$, an
# independent transversal on $V'_{J_1}$ which satisfies $\mathbf{Q}_1$.
# Since $\tau \leq \frac{2 \log n}{\log \log n}$, this property implies that each $V_k$
# with $k \not \in I_1 \cup J_1$ has $O\big(\tau \frac{\Delta}{\log n}\big) = o(\Delta)$
# vertices with neighbors in $U_1$.
# 
# Finally, let $K = [r] \setminus (I_1 \cup J_1)$.  Delete all neighbors of $T_1 \cup U_1$
# and all locally big vertices from every $V_k$ with $k\in K$, and denote the resulting sets
# by $V'_k$. All $V'_k$ will still have size at least $\big(1 + \frac{\ep}{2}\big) \Delta$,
# but now no vertex there has more than $\frac{\Delta}{\log n}$ neighbors in any single set $V_k'$.
# Thus, the following result from \cite{LS} implies that for sufficiently large $n$, there
# is an independent transversal on $V'_K$, which completes $T_1 \cup U_1$ into an
# independent transversal through all parts.
#   """
# context_4 = r""" entries of $M_n$ satisfy this property, then
# the probability that $M_n$ is singular is at most $\lt(p^{1/r} + o(1)\rt)^n$.
# All of the results in this paper hold for any characteristic zero integral
# domain replacing the complex numbers.
# 
# 
# In the special case where the entries of $M_n$ are  ``fair coin flips''
# (taking the values $+1,-1$ each with probability $1/2$), our general bound
# implies that the probability that $M_n$ is singular is at most
# $\lt(\frac{1}{\sqrt2}+o(1)\rt)^n$, improving on the previous best upper bound
# of $\lt(\frac{3}{4}+o(1)\rt)^n$, proved by Tao and Vu \cite{TV2}.
# 
# 
# In the special case where the entries of $M_n$ are  ``lazy coin flips''
# (taking values $+1,-1$ each with probability $1/4$ and value 0 with probability $1/2$), our general bound implies  that
# the probability that $M_n$ is singular is at most
# $\lt(\frac{1}{2}+o(1)\rt)^n$, which is asymptotically sharp.
# 
# Our method is a refinement of those  from \cite{KKS} and \cite{TV2}. In
# particular,  we  make a critical use of the Structure Theorem from
# \cite{TV2}, which was obtained using tools from additive combinatorics.
# 
#   \end{abstract}
# 
# \section {Introduction}\label{s:intro}
# 
# Let $n$ be a large integer and $M_n$ be an $n$ by $n$ random matrix whose
# entries are independent (but not necessarily identically distributed) discrete
# random variables taking values in the complex numbers. The problem of
# estimating the probability that $M_{n}$ is singular is a basic problem in the
# theory of random matrices and combinatorics.  The goal of this paper is to
# give a bound that applies to a large variety of distributions. The general
# statement (Theorem~\ref{main theorem}) is a bit technical, so we will first
# discuss a few corollaries concerning special cases.
# 
# 
# The most famous special  case is when the entries of $M_{n}$ are
# independent identically distributed (i.i.d.) Bernoulli random variables
# (taking values $\pm 1$ with probability $1/2$). The following conjecture has
# been open for quite some time: """
# context_5 = r""" rtex-disjoint heterochromatic trees. In \cite{chen},
# the authors determined the heterochromatic tree partition number
# of an $r$-edge-colored complete bipartite graph $K_{m,n}$. In this
# paper we consider an $r$-edge-colored complete graph $K_{n}$ and give
# the exact expression for its heterochromatic tree partition number. \\
# 
# Before proceeding, we introduce some definitions and notations.
# Throughout this paper, we use $r$ to denote the number of the
# colors, and an $r$-edge-coloring of a graph $G$ means that each
# color appears at least once in $G$. Let $\phi$ be an
# $r$-edge-coloring of a graph $G$. For an edge $e\in E(G)$, denote
# by $\phi(e)$ the color of $e$. Denote by $t_r(G, \phi)$ the
# minimum positive integer $p$ such that under the $r$-edge-coloring
# $\phi$, the vertices of $G$ can be covered by at most $p$
# vertex-disjoint heterochromatic trees. Clearly, $t_r(G)=\max
# _{\phi} t_r(G, \phi)$, where $\phi$ runs over all
# $r$-edge-colorings of the graph $G$. Let $\phi$ be an
# $r$-edge-coloring of the graph $G$ and $F$ be a spanning forest of
# $G$, each component of which is a heterochromatic tree. If $F$
# contains exactly $t_r(G, \phi)$ components, then $F$ is called an
# {\it optimal heterochromatic tree partition} of the graph $G$ with
# edge-coloring $\phi$. Note that a tree consisting of a single
# vertex is also regarded as a heterochromatic tree. \\
# 
# For any integer $r\geq 2$, there is a unique positive integer $t$,
# such that ${t\choose 2} +2\leq r\leq {{t+1}\choose 2} +1$.
# Clearly, the integer $t$ is determined completely by $r$, and here
# we denote it by $f(r)=t$. This integer $f(r)=t$ will play an
# important role in expressing the number $t_r(K_n)$. If the color
# number $r=1$, clearly a maximum matching (plus a single vertex
# when $n$ is odd) in $K_n$ is an optimal heterochromatic tree
# partition, and then $t_r(K_n)=\lceil \frac{n}{2} \rceil$. So, in
# the rest of this paper we only consider the case $2\leq r\leq
# {n\choose 2}$. The following is the main result of this paper.  """
# context_6 = """ })=(1 \pm \eps)n/\sqrt{\log_b n}$,
# where $b:=1/(1-p)$. Here~$G_{n,p}$ is a random graph on~$n$ vertices
# where the edges are present independently and with probability~$p$.
# We say that an event occurs \emph{asymptotically almost surely} (a.a.s.)
# if it occurs with probability tending to~$1$ as~$n$ tends to infinity.
# 
# Krivelevich and Sudakov~\cite{KS} considered the order of the largest
# complete minor in a sparser random graph (and more generally in arbitrary
# pseudo-random and expanding graphs).
# %They observed that the proof in~\cite{BCE} can be extended to the case
# %$p \to 0$ as long as $p$ is not too small, but that it breaks down eventually.
# They determined the order of magnitude of~ccl$(G_{n,p})$
# as long as~$p\ge n^{\eps-1}$. Our first result determines~ccl$(G_{n,p})$ asymptotically
# as long as $p\ge C/n$ and $p=o(1)$.
# 
# \begin{thm}\label{thmdense}
# For every $\eps>0$ there exists a constant $C=C(\eps)$ such that if $pn\ge C$
# and $p=o(1)$, then a.a.s.
# $${\rm ccl}(G_{n,p})=(1\pm \eps) \sqrt{\frac{n^2p}{\ln (np)}}. $$
# \end{thm}
# 
# One can combine Theorem~\ref{thmdense} with~\cite{BCE} to obtain
# a single formula which allows for constant~$p$ as well. Indeed, let $b:=1/(1-p)$.
# If $p=o(1)$ a series expansion gives $\ln b=-\ln (1-p)=p+O(p^2)$.
# Thus
# $$
# \sqrt{\frac{n^2p}{\ln (np)}} = \sqrt{\frac{n^2 p}{\ln b\log_b (np)}}
# =(1+o(1)){n \over \sqrt{\log_b (np)}}.
# $$
# Also if~$p$ is constant, then $\log_b n=(1+o(1))\log_b(np)$.
# So altogether we obtain the following.
# \begin{corollary}\label{thmdense1}
# For every  $\eps>0$ there exists a constant $C=C(\eps)$ such that if $C/n \le p \le 1-\eps$,
# then a.a.s.
# $${\rm ccl}(G_{n,p})=(1\pm \eps) \frac{n}{\sqrt{\log_{b} (np)}}. $$
# \end{corollary}
# 
# In the last section of the paper, we estimate~ccl$(G_{n,c/n})$ where $c>1$ is fixed.
# Krivelevich and Sudakov~\cite{KS} observed that there are constants~$c_1$ and~$c_2$
# such that $c_1\sqrt{n /\log n}\le {\rm ccl}(G_{n,c/n})\le c_2\sqrt{n}$
# and asked what the correct order of magnitude is.
#  """
# context_7 = r""" recting.
# % \marginal{Is the terminology correct?}
# % We can detect up to $r$ simultaneous errors when these code words have
# %   Hamming distance at least $r+1$, which is exactly when $G\in
# %   \Gr(n,n-r)$, see \refT{karakterisointi}.
# % Similarly, we can correct up to $r$ simultaneous errors when these
# %   code words have Hamming distance at least $2r$, which is exactly when $G\in
# %   \Gr(n,n-2r+1)$.
# % \end{rem}
# 
# 
# We give some basic results in \refS{Sbasic}, including our
# first upper bound on $\NN(k)$.
# A better bound, based on a relation with error-correcting codes,
# is given in \refS{Supper}, but we first
# study small $k$ in \refS{Ssmall}, where we give a complete
# description of the sets $\Gr(k)$ for $k\le 4$ and find $\NN(k)$ for
# $k\le 6$.
# We consider strongly regular graphs and some modifications of them in
# \refS{sec:strong}; this provides us with examples (e.g., Paley graphs)
# that attain or almost attain the upper bound in \refT{T2}.
# In \refS{Ssmaller} we consider the probability that a random subset of
# $s$ vertices in a graph $G\in\Gr(n,k)$ is identifying (for $s<k$); in
# particular, this yields results on the size of the smallest
# identifying set.
# In \refS{Sell} we give some results for the case $\ell\ge2$.
# 
# 
# 
# 
# \section{Some basic results}\label{Sbasic}
# 
# We begin with some simple consequences of the definition.
# 
# \begin{lemma}\label{L1}
#   \begin{romenumerate}
# 	\item\label{L1a}
# If $G\in \Gr(n,k,\ell)$, then $G\in \Gr(n,k',\ell')$
# whenever $k\le k'\le n$ and $1\le\ell'\le\ell$.
# \item\label{L1b}
# If $G=(V,E)\in \Gr(n,k,\ell)$, then every induced
# subgraph $G[A]$, where $A\subseteq V$, of order $|A|=m\ge k$ belongs to
# $\Gr(m,k,\ell)$.
# \item\label{L1c}
# If $\Gr(n,k)=\emptyset$, then $\Gr(n',k)=\emptyset$ for all $n'\ge n$.
#   \end{romenumerate}
# \end{lemma}
# \begin{proof}
#   Parts \ref{L1a} and \ref{L1b} are straightforward to verify. For \ref{L1c}, note
#   that any subset of $n$ vertices of a graph in $\Gr(n',k)$
# would induce a graph in $\Gr(n,k)$ by \ref{L1b}.
# \end{proof} """
# context_8 = """  """
# context_9 = """  """
# context_10 = """  """
# 
# theorem_1 = r"""
# %3.1
# A restricted set $B$ is closed.
# 
# 
# 
# %Lemma 3.2.
# Let $N=(V,A,r,X)$ be an acyclic $X$-network.  Suppose $B$ is restricted and $r \notin B$.  For every $b \in B$ there is a directed path from $Anc(B)$ to $b$ such that all vertices on the path except $Anc(B)$ itself lie in $B$.
# 
# 
# %3.4
# Suppose $B$ and $C$ are restricted sets and there is an arc $(b,c)$ with $b \in B$ and $c \in C$.  Then $B \cup C$ is restricted.
# %If $r \notin B$ then  $Anc(B \cup C) = Anc(B)$.
#  """
# theorem_2 = r"""
# \label{thm:k-crossing-A}
#   There is an explicit bijection on set partitions, preserving the set of
#   openers and the set of closers, and interchanging the cardinalities of the
#   maximal crossing and the maximal nesting.
# 
# 
# 
# \label{thm:crossings-C}
#   There is an explicit bijection on set partitions of type $C$, preserving the
#   set of openers and the set of closers, and interchanging the number of
#   crossings and the number of nestings.
# 
# 
# \label{thm:k-crossing-C}
#   There is an explicit bijection on set partitions of type $C$, preserving the
#   set of openers and the set of closers, and interchanging the cardinalities of
#   the maximal crossing and the maximal nesting.
# 
# 
# There is an explicit bijection on set partitions of type $B$, preserving the
#   set of openers and the set of closers, and mapping the number of nestings to
#   the number of crossings.
# 
# 
# \label{thm:k-crossing-B}
#   There is an explicit bijection on set partitions of type $B$, preserving the
#   set of openers and the set of closers, and interchanging the cardinalities of
#   the maximal crossing and the maximal nesting.
# 
# """
# theorem_3 = r"""
# \label{lem:first-stage}
#   Suppose $t > 1$, and $T_t$ is an independent transversal on $V_{I_t}$ which satisfies
#   $\mathbf{P}_t$.  Then we can extend $T_t$ to $T_{t-1}$, an independent transversal on
#   $V_{I_{t-1}}$ which satisfies $\mathbf{P}_{t-1}$.
# 
# 
# \label{lem:second-stage}
#   Suppose $t > 1$, and $U_t$ is an independent transversal on $V'_{J_t}$ which satisfies
#   $\mathbf{Q}_t$.  Then we can extend $U_t$ to $U_{t-1}$, an independent transversal on
#   $V'_{J_{t-1}}$ which satisfies $\mathbf{Q}_{t-1}$.
# 
# 
# \label{thm:main}
#   Let $\Delta$ be the maximum degree of the random graph $\gnp$, where $p < 1-\theta$
#   for any arbitrary constant $\theta > 0$.
#   \begin{description}
#   \item[\hspace{12pt}\textbf{(i)}] If $p \gg \left(\frac{\log^4 n}{n}\right)^{1/3}$, then
# almost surely the strong chromatic
#     number of $\gnp$ equals $\Delta+1$.
# \item[\hspace{12pt}\textbf{(ii)}] If $p \gg \left(\frac{\log n}{n}\right)^{1/2}$, then a.s.\ the strong chromatic
#     number of $\gnp$ is $(1+o(1))\Delta$.
#   \end{description}
# 
# 
# 
# \label{thm:main2}
# Let $\Delta$ be the maximum degree of the random graph $\gnp$. If
# $p \geq \frac{\log^4 n}{n}$,
# then almost surely every collection of disjoint subsets $V_1, \ldots, V_r$ of $\gnp$ with all
# $|V_i|\geq (1+o(1))\Delta$ has an independent transversal.
#  """
# theorem_4 = r"""
# \label{noSthm}
# For every $\epsilon >0$ there exists $\delta>0$ such that the following holds.
# Let $\fmat$ be an $n$ by $n$ complex matrix in which $\fxt$ rows contain
# fixed, non-random entries and where the other rows contain entries that are
# independent discrete random variables.  If the fixed rows have co-rank $k$ and
# if for every random entry $\alpha$, we have $\max_x \Pr(\alpha = x) \le
# 1-\epsilon$, then for all sufficiently large $n$
# $$\Pr(\fmat \mbox{ has co-rank } >k)\le (1-\delta)^{n-\fxt}.$$
# %
# %$\fxt$ linearly independent rows
# %containing fixed complex numbers and with the remaining rows containing
# %independent discrete random variables, and if for every random entry $\alpha$
# %we have
# %$\max_x\Pr(\alpha=x) \le 1-\epsilon$, then
# %$$\Pr(M_n \mbox{ is singular}) \le (1-\delta)^{n-\fxt}.$$
# %
# 
# 
# 
# [\cite{VWnote}]\label{reduction theorem}
# Let $\sov$ be a finite subset of $\bb C$.  There exist infinitely many
# primes $Q$ such that there is a ring homomorphism $\qmap:\Z[\sov] \to \Zmodp$
# satisfying the following two properties:
# \begin{enumerate}
# \item[(i)]  the map $\qmap$ is injective on $\sov$, and
# \item[(ii)]  for any $n$ by $n$ matrix $(s_{ij})_{1\le i,j\le n}$ with entries $s_{ij}\in S$,
# we have $$\det\lt(\rule{0pt}{14pt}(s_{ij})_{1\le i,j\le n}\rt) = 0 \quad\mbox{ if and only if } \quad
# \det\left(\rule{0pt}{14pt}(\qmap(s_{ij}))_{1\le i,j\le n}\right)=0.$$
# \end{enumerate}
# 
# 
# 
# [Small combinatorial dimension, \cite{KKS}, \cite{TV1}, \cite{TV2}]
# \label{smalldim}
# For any $\delta >0$ we have
# \[
# \sum_{\dpm \in \MC D \ \mathrm{s.t.}\ p^{n-\dpm}\le \delta^n}
# \quad
# \sum_{V \in \Gr(\dpm)} \probability(A_V) \le n \delta^n.
# \]
# 
# 
# 
# [Large combinatorial dimension, \cite{KKS},\cite{TV1},\cite{TV2}]\label{large dim}
# We have
# \[
# \sum_{\dpm \in \MC D \ \mathrm{s.t.}\ \frac{\largedimconstant}{\sqrt n}\le p^{n-\dpm}}
# \quad
# \sum_{V \in \Gr(\dpm)} \probability(A_V) \le (p+\littleo{1})^n
# \]
# """
# theorem_5 = r"""
# \label{inequ}
# $t_{r+1}(K_n)\leq t_{r}(K_n)$.
# 
# 
# \label{cutedge}
# Let $G$ be a simple graph of order $n$. If $G$ contains a
# cut-edge, then $|E(G)|\leq {{n-1}\choose 2}+1$.\qed \\
# """
# theorem_6 = r""" \begin{theorem}[Bollobás, Catlin, Erdős, 1980]
# \label{thm:bce_hadwiger}
# For almost every graph $G$ on $n$ vertices, the contraction clique number, denoted as $ccl(G)$, satisfies:
# \[
# (1-\epsilon) \frac{n}{\sqrt{\log_2 n}} \le ccl(G) \le (1+\epsilon) \frac{n}{\sqrt{\log_2 n}}
# \]
# for any $\epsilon > 0$ as $n \to \infty$.
# \end{theorem}
# 
# 
#  \begin{theorem}[Krivelevich, Sudakov]
# \label{thm:ks_expanders}
# Let $G$ be an $(n, d, \lambda)$-graph. Then $G$ contains a complete minor of size at least $\frac{d}{2\lambda}$.
# \end{theorem}
# 
# 
# \begin{theorem}[Kostochka, Thomason]
# \label{thm:kostochka_thomason}
# Every graph with an average degree of $d$ has a complete minor of order $\Omega\left(\frac{d}{\sqrt{\log d}}\right)$.
# \end{theorem}"""
# theorem_7 = r"""
# \label{Tcond}
# Suppose that $G=(V,E)\in \Gr(n,k,\ell)$,
# where $n>k$ and $\ell\ge2$.
# Then the following conditions hold:
# \begin{romenumerate}
#  \item For all $x\in V$ we have $\ell+1< n-k+\ell+1\le |N[x]|\le
#  k-\ell$.
# In other words, $\gd_G\ge n-k+\ell$ and $\Delta_G\le k-\ell-1$.
#  \item For all $x,y\in V$, $x\ne y$, $|N[x]\cap N[y]|\le k-2\ell+1$.
# \item
# $n\le 2k-2\ell-1$ and $k\ge 2\ell+2$.
# \end{romenumerate}
# 
# 
# \label{GoodL}
# For $\ell\geq 2$, $\NN(k,\ell)\le \max\bigset{\frac{\ell}{\ell-1}(k-2),k}$.
# 
# 
# \label{Tl2}
#   If $k\le 5$, then $\Xi(k,2)=k$. If $k\ge6$, then
# $$\Xi(k,2)< \Bigpar{1+\frac{1}{\sqrt{2}}}(k-2)+\frac14.$$
# 
# 
# 
# Let $\ell\ge 2$ and $m\ge \max\{2\ell-2,4\}$. A binary hypercube of
#  dimension $m$ belongs to $\Gr(2^m,2^m-m+2\ell-2,\ell)$
# 
# 
# The smallest $n\ge2$ such that there exists a connected graph (or a
# graph without isolated vertices) in $\Gr(n,n,2)$ is $n=7$. """
# 
# prompt_end = """
# Task:
# Based on the theorems and abstarct above, state and rigorously formulate a new theorem or conjecture."""
# 
# 
# 
# defintions_1 =r""" You are a mathematician specializing in phylogenetic combinatorics and graph theory. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, here are some definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{X-network:} An X-network $N = (V, A, r, X)$ is a digraph $(V, A)$ with root $r$ such that
#     (1) there is a one-to-one map $\phi : X \to V$ such that the image of $\phi$ is the set of
#     all leaves of $(V, A)$, and
#     (2) for every $v \in V$ there is a leaf $u$ and a directed path from $v$ to $u$.
#     Thus the set of leaves of $N$ may be identified with the set $X$; every vertex is
#     ancestral to a leaf.
#     In biology most X-networks are acyclic. The set $X$ provides a context for $N$,
#     giving a hypothesized relationship among the members of $X$. For convenience,
#     we will write $x$ for the leaf $\phi(x)$.
#     \item \textbf{X-tree:} An X-tree is an X-network such that the underlying digraph is a rooted tree.
#     \item \textbf{Digraph:} A directed graph or digraph $N = (V, A)$ consists of a finite set $V$ of vertices and a finite set $A$ of arcs, each consisting of an ordered pair $(u, v)$ where $u \in V, v \in V, u \neq v$.
#     \item \textbf{Connected:} A graph $G = (V, E)$ is connected if, given any two distinct $v$ and $w$ in $V$ there exists a sequence $v = v_0, v_1, v_2, \dots , v_k = w$ of vertices such that for $i = 0, \dots , k-1$, $\{v_i , v_{i+1}\} \in E$. A subset $W$ of $V$ is connected if the induced subgraph $G[W]$ is connected.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
# """
# defintions_2 =r"""You are a mathematician specializing in enumerative and algebraic combinatorics. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{Set Partition:} A \Dfn{set partition} of $[n]:= \{1,2,3,\ldots,n\}$ is a collection $\mathcal{B}$ of pairwise disjoint, non-empty subsets of $[n]$, called \Dfn{blocks}, whose union is $[n]$.
#     \item \textbf{Crossing:} For ordinary set partitions, a
#     \Dfn{crossing} consists of a pair of arcs $(i,j)$ and $(i',j')$ such that
#     $i<i'<j<j'$:
#     \begin{center}
#       \setlength{\unitlength}{20pt}
#       \begin{picture}(12,2.2)
#         \put(0,0){\hbox{$1$}}
#         \put(1,0){\hbox{$\ldots$}}
#         \put(2.5,0){\hbox{$i$}}
#         \put(3.5,0){\hbox{$<$}}
#         \put(4.75,0){\hbox{$i'$}}
#         \put(5.75,0){\hbox{$<$}}
#         \put(7,0){\hbox{$j$}}
#         \put(8,0){\hbox{$<$}}
#         \put(9.25,0){\hbox{$j'$}}
#         \put(10.25,0){\hbox{$\ldots$}}
#         \put(11.75,0){\hbox{$n$}}
#         \qbezier(2.9,0.7)(4.9,3.2)(6.9,0.7)
#         \qbezier(5.1,0.7)(7.1,3.2)(9.1,0.7)
#       \end{picture}
#     \end{center}
#     \item \textbf{Nesting:} If $i<i'<j'<j$, we have a \Dfn{nesting}, pictorially:
#     \begin{center}
#       \setlength{\unitlength}{20pt}
#       \begin{picture}(12,2.2)
#         \put(0,0){\hbox{$1$}}
#         \put(1,0){\hbox{$\ldots$}}
#         \put(2.5,0){\hbox{$i$}}
#         \put(3.5,0){\hbox{$<$}}
#         \put(4.75,0){\hbox{$i'$}}
#         \put(5.75,0){\hbox{$<$}}
#         \put(7,0){\hbox{$j'$}}
#         \put(8,0){\hbox{$<$}}
#         \put(9.25,0){\hbox{$j$}}
#         \put(10.25,0){\hbox{$\ldots$}}
#         \put(11.75,0){\hbox{$n$}}
#         \qbezier(2.9,0.7)(6.0,3.2)(9.1,0.7)
#         \qbezier(5.1,0.7)(6.0,2.2)(6.9,0.7)
#       \end{picture}
#     \end{center}
#     A set partition of $[n]$ is called \Dfn{non-crossing} (resp. \Dfn{non-nesting})
#     if the number of crossings (resp. the number of nestings) equals $0$.
#     \item \textbf{Opener and Closer:} The \Dfn{openers} $\op(\mathcal{B})$ are the non-maximal elements of the blocks in $\mathcal{B}$, whereas the \Dfn{closers} $\cl(\mathcal{B})$ are its non-minimal elements.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
# """
# defintions_3 ="""You are a mathematician specializing in \textbf{probabilistic and extremal combinatorics}, with a focus on random graphs. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{Proper k-coloring:} Let $G$ be a graph with $n$ vertices, and let $k$ be an integer dividing $n$.  $G$ is said to be strongly $k$-colorable if for every partition of $V(G)$ into disjoint sets $V_1 \cup \dots \cup V_r$, all of size exactly $k$, there exists a proper vertex $k$-coloring of $G$ with each color appearing exactly once in each $V_i$.
#     \item \textbf{Strongly k-colorable:} In the case when $k$ does not divide $n$, $G$ is defined to be strongly $k$-colorable if the graph obtained by adding $k \big\lceil \frac{n}{k} \big\rceil - n$ isolated vertices is strongly $k$-colorable. The strong chromatic number of $G$ is the minimum $k$ for which $G$ is strongly $k$-colorable.
#     \item \textbf{Strong Chromatic Number, $\chi_s(G)$:} The minimum integer $k$ for which $G$ is strongly $k$-colorable.
#     \item \textbf{Independent Transversal:} An \emph{independent transversal} with respect to $\{V_i\}_{i=1}^r$ is an independent set in $G$ which contains exactly one vertex from each $V_i$.
#     \item \textbf{Maximum Degree, $\Delta(G)$:} The largest degree of any vertex in the graph $G$.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
#  """
# defintions_4 ="""You are a mathematician specializing in random matrix theory and additive combinatorics. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{Discrete Random Matrix $M_n$}: Let $n$ be a large integer and $M_n$ be an $n$ by $n$ random matrix whose entries are independent (but not necessarily identically distributed) discrete random variables taking values in the complex numbers.
#     \item \textbf{Bernoulli Random Matrix $M_{\pm 1,n}$}: The specific case where each entry is chosen independently and uniformly from $\{-1, +1\}$ (i.e., with probability 1/2 for each value).
#     \item \textbf{Singularity Probability}: The probability that a random matrix $M_n$ is singular, i.e., $\Pr(\det(M_n) = 0)$.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
#  """
# defintions_5 ="""You are a mathematician specializing in extremal and probabilistic graph theory. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{$r$-edge-coloring:} An assignment of $r$ distinct colors to the edges of a graph $G$. It is assumed every color is used at least once.
#     \item \textbf{Heterochromatic Tree:} A \emph{heterochromatic tree} is an edge-colored tree in which any two edges have different colors.
#     \item \textbf{Heterochromatic Tree Partition:} A partition of the vertex set $V(G)$ into a collection of vertex-disjoint heterochromatic trees.
#     \item \textbf{Heterochromatic Tree Partition Number, $t_r(G)$:} The \emph{heterochromatic tree partition number} of an $r$-edge-colored graph $G$, denoted by $t_r(G)$, is the minimum positive integer $p$ such that whenever the edges of the graph $G$ are colored with $r$ colors, the vertices of $G$ can be covered by at most $p$ vertex-disjoint heterochromatic trees.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
#  """
# defintions_6 = """You are a mathematician specializing in probabilistic combinatorics and the theory of random graphs. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{Random Graph $G(n,p)$:} A graph on $n$ labeled vertices where each of the $\binom{n}{2}$ possible edges is present independently with probability $p$.
#     \item \textbf{Graph Minor:} A graph $H$ is a \emph{minor} of $G$ if for every vertex $h \in V(H)$ there is a connected subset $B_h \subseteq V(G)$ such that all the $B_h$ are disjoint and $G$ contains an edge between $B_h$ and $B_{h'}$ whenever $hh'$ is an edge of $H$.
#     \item \textbf{Contraction Clique Number, $\mathrm{ccl}(G)$:} The largest integer $k$ such that $K_k$ is a minor of $G$.
#     \item \textbf{Asymptotically Almost Surely (a.a.s.):} An event occurs with probability tending to 1 as the number of vertices $n$ tends to infinity.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
#  """
# defintions_7 =""" You are a mathematician specializing in combinatorics and graph theory, with a focus on identifying codes and extremal problems. Your task is to read the provided mathematical context and generate a plausible, non-trivial theorem or conjecture that logically follows from it. To ensure you understand the specific vocabulary, use the following definitions.
# 
# \subsection*{Definitions}
# \begin{enumerate}
#     \item \textbf{Closed Neighborhood $N[x]$:} For a vertex $x$ in a graph $G$, its closed neighborhood $N[x]$ is the set containing $x$ and all vertices adjacent to $x$.
#     \item \textbf{Identifying Set (or Identifying Code):} A subset of vertices $C$ is an identifying set if for every vertex $x$, the set $N[x] \cap C$ is non-empty, and for any two distinct vertices $x$ and $y$, $N[x] \cap C \neq N[y] \cap C$.
#     \item \textbf{$k$-Universally Identifying Graph:} A graph $G$ is $k$-universally identifying if \emph{every} subset of its vertices of size $k$ is an identifying set.
# \end{enumerate}
# 
# \subsection*{Mathematical Context}
#  """
# 
# 
# 
# defns = [defintions_1,defintions_2,defintions_3,defintions_4,defintions_5,defintions_6,defintions_7]
# 
# defintions_end = """
# 
# 
# Task:
# Based on the definitions and context above, state and rigorously formulate a new theorem or conjecture.
# """
# 
# prompts = []
# outputs = []
# 
# system_prompt = """You are an expert in mathmatics, who can write a logical theorem that could be useful for the paper provided."""
# abs = [abstract_1, abstract_2, abstract_3, abstract_4, abstract_5, abstract_6, abstract_7]
# contexts = [context_1, context_2, context_3, context_4, context_5, context_6, abstract_7]
# thms = [theorem_1,theorem_2,theorem_3,theorem_4,theorem_5,theorem_6,theorem_7]

for defn, con in zip(defns, contexts):
    researchprooooompt = defn + con + defintions_end

    l = researchprooooompt
    prompts.append(l)
    # reseracher
    if checkpoint in chat_models:
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": researchprooooompt}
        ]

        final_prompt_string = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)

        out = pipe(final_prompt_string, max_new_tokens=max_tokens, return_full_text=False)
        print(out[0]['generated_text'])
        researcheroutput = out[0]['generated_text']
        r = researcheroutput
        outputs.append(r)



# --- THIS IS THE MODIFIED CODE BLOCK ---

# Define the directory where results will be saved
output_dir = "inference_newmodelDEFS"
# Create the directory; exist_ok=True prevents an error if it already exists
os.makedirs(output_dir, exist_ok=True)

print(f"Saving {len(prompts)} results to the '{output_dir}' directory...")

try:
    # Loop through each prompt and output pair
    for n, (p, o) in enumerate(zip(prompts, outputs)):
        # Create a unique filename for each result, e.g., "results1.txt", "results2.txt"
        # The (n + 1) makes the numbering start at 1 instead of 0
        file_path = os.path.join(output_dir, f"results{n + 1}.txt")

        # Open the individual file and write the content
        with open(file_path, "w", encoding="utf-8") as file:
            file.write(f"Below is the prompt for result #{n + 1}:\n")
            file.write(p + "\n\n") # Added extra newline for readability
            file.write(f"--- Model Generation for result #{n + 1} ---\n")
            file.write(o + "\n")
    print("Successfully saved all results.")

except Exception as e:
    print(f"An error occurred while writing to files: {e}")